# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Tech Blog
description: "My Online Reminder"
keywords: "Tech, Dev, Life Hack"
url: http://silefort.github.io
baseurl: ""

# google_analytics: UA-52446115-1
repo: http://github.com/silefort/silefort.github.io
disqus_shortname: "silefort"
disqus_site_shortname: "silefort"

# Author settings
author:
  name      : Simon
  bio       : "#Dev, #Tech, #LifeHacking"
  thumb     : /images/profile.jpg
  email     : simon.lefort@gmail.com
  url       : http://silefort.github.io
  github    : http://github.com/silefort
  twitter   : http://twitter.com/si_lefort
  linkedin  : http://linkedin.com/in/simon-lefort-b6698661

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]